#!/usr/bin/env python3
import sys
import os

name = sys.argv[-1]
if name[-2:] == ".v":
    name = name[:-2]
os.system(
    f"verilator --cc --exe --build {name}_sim.cpp {name}.v")
if "-x" in sys.argv:
    os.system(f"./obj_dir/V{name}")
